name = "ai-dev-docs"
main = ".open-next/worker.js"
compatibility_date = "2025-09-02"
compatibility_flags = ["nodejs_compat"]
account_id = "eb7be4c6bce750dfd220cdd7cf4abe55"

[assets]
binding = "ASSETS"
directory = ".open-next/assets"
